#!/bin/sh

show_logo()
{
	cat <<EOF

                          :::::::::   +#+    :::   :::    :::::::::
             (/;         :+:    :+:        :+:+: :+:+:   :+:    :+:
      .--..-(/;         +:+    +:+  +:+  +:+ +:+:+ +:+  +:+    +:+
      |    (/;         +#++:++#+   +#+  +#+  +:+  +#+  +#++:++#+
    __|====/=|__      +#+         +#+  +#+       +#+  +#+
   (____________)    #+#         #+#  #+#       #+#  #+#
                    ###         ###  ###       ###  ###

                                          raspberry pi music player
                                                    -- -     -
EOF
}

#  Copyright (c) 2022-2026 Steven Peguero (stevenpeguero.com)
#  Source is licensed under MIT License. Refer to LICENSE file for details.

_sys="$(uname -s | tr '[:upper:]' '[:lower:]')"

_bin_fzf='fzf'
_bin_mus='mpv'
_bin_snd='sox'
_bin_tts=

if [ ! "${_sys}" = 'darwin' ]
then
	_bin_tts='espeak'
else
	_bin_tts='say'
fi

_depends_dire="pimp ${_bin_fzf} ${_bin_mus}"
_depends_optional="${_bin_tts} ${_bin_snd}"
_params="$(printf '%s\n' "$*" | awk '{$1=""; print}' | sed 's/^[[:space:]]*//g')"

PIMP_DEBUG="${PIMP_DEBUG-0}"
PIMP_DPATH_CACHE="${PIMP_DPATH_CACHE-"${HOME}/.cache/pimp"}"
PIMP_DPATH_CONFG="${PIMP_DPATH_CONFG-"${HOME}/.config/pimp"}"
PIMP_DPATH_MUSIC="${PIMP_DPATH_MUSIC-"${HOME}/Music"}"
PIMP_DPATH_SHARE="${PIMP_DPATH_SHARE-"${HOME}/.local/share/pimp"}"
PIMP_DPATH_SHARE_SOUND="${PIMP_DPATH_SHARE}/sound"
PIMP_DPATH_STATE="${PIMP_DPATH_STATE-"${HOME}/.local/state/pimp"}"
PIMP_DPATH_STATE_PBACK="${PIMP_DPATH_STATE}/playback"
PIMP_FPATH_STATE_PLIST="${PIMP_DPATH_STATE}/playlist"

export PIMP_SCRIPT=  #  allows users to make use of mpv lua scripts while also enforcing
                     #  pimp-exclusivity. to enable this, use this at beginning of said scripts:
                     #
                     #  ```
                     #  local os          = require 'os'
                     #  local pimp_script = os.getenv("PIMP_SCRIPT")
                     #
                     #  if not pimp_script then
                     #      return 1
                     #  end
                     #  ```
                     #
                     #  scripts should be stored within "$HOME/.config/mpv/scripts".

show_dname_fzf()
{
	#  synopsis:  shows recursive and interactive list of directories to play.

	local opt="$(_params_opt "$*")"
	local str="$(_params_str "$*")"

	if _exists_opt b "${opt}"
	then
		#  omits opt to resume "play" tonal sound at start of music playback.
		local opt="$(printf '%s' "${opt}" | tr -d b)"
	fi

	local dpath_music="${PIMP_DPATH_MUSIC}"
	local fzf_opt=
	local fzf_query="${str}"

	export PIMP_CALLED_VIA_DPATH_DISPLAY=  #  allows another function to determine whether
	                                       #  it was called via this specific function.

	if [ -n "${opt}" ]
	then
		local fzf_opt="-${opt}"
	fi

	set_terminal_title

	find -L "${dpath_music}" -type d | \
	cut -d '/' -f "$(print_cut_field_selection_number)" | sed '/^$/d' | sed '1i\
.
	' | sort -r | \
	"${_bin_fzf}" -i -s -m -e \
		--header 'pimp (dir)' \
		--header-first \
		--border rounded \
		--color fg+:16,bg+:10,hl:9,hl+:1,gutter:1 \
		--prompt '> ' \
		--algo v1 \
		--query "${fzf_query}" \
		--literal \
		--cycle \
		--tac \
		--layout reverse \
		--preview "pkill -x ${_bin_tts}; pimp app-speech ${fzf_opt} {}; pimp app-tone high ${fzf_opt}" \
		--preview-window 0% \
		--bind "enter:execute(pkill -x ${_bin_tts}; pimp app-rmpp; pimp play -ds ${fzf_opt} {}; pimp app-tone high ${fzf_opt})" \
		--bind "double-click:execute(pkill -x ${_bin_tts}; pimp app-rmpp; pimp play -ds ${fzf_opt} {}; pimp app-tone high ${fzf_opt})" \
		--bind "insert:execute-silent(pkill -x ${_bin_tts}; pimp app-tone ffgo ${fzf_opt})+execute(pimp file ${fzf_opt})+execute-silent(pimp app-tone ffbk ${fzf_opt})" \
		--bind "f5:execute-silent(pkill -x ${_bin_tts}; pimp app-tone ffgo ${fzf_opt})+execute(pimp file ${fzf_opt})+execute-silent(pimp app-tone ffbk ${fzf_opt})" \
		--bind "f6:execute(pkill -x ${_bin_tts}; pimp play ${fzf_opt}; pimp app-tone high ${fzf_opt})" \
		--bind "*:execute(pkill -x ${_bin_tts}; pimp play ${fzf_opt}; pimp app-tone high ${fzf_opt})" \
		--bind 'change:first' \
		--bind 'bspace:clear-query' \
		--bind 'home:first' \
		--bind 'end:last' \
		--bind "esc:execute(pkill -x ${_bin_tts})+abort" \
		--bind "tab:execute(pkill -x ${_bin_tts})+abort" \
		--bind "alt-q:execute(pkill -x ${_bin_tts})+abort" \
		--bind "ctrl-q:execute(pkill -x ${_bin_tts})+abort"
}

show_fpath_fzf()
{
	#  synopsis:  shows recursive and interactive list of files to play.

	local opt="$(_params_opt "$*")"
	local str="$(_params_str "$*")"

	if _exists_opt b "${opt}"
	then
		#  omits opt to resume "play" tonal sound at start of music playback.
		local opt="$(printf '%s' "${opt}" | tr -d b)"
	fi

	local cmd_pimp_quit='10_cmd_filter_quit'
	local cmd_pimp_refresh='20_cmd_filter_refresh'
	local cmd_pimp_resume_pback='30_cmd_resume_pback'
	local dpath_music="${PIMP_DPATH_MUSIC}"
	local fpath_state_plist="${PIMP_FPATH_STATE_PLIST}"
	local fzf_opt=
	local fzf_query="${str}"
	local i=0
	local int_modtime_plist_preloop="$(get_file_modtime "${fpath_state_plist}")"
	local int_modtime_plist_pstloop=

	if [ -n "${opt}" ]
	then
		local fzf_opt="-${opt}"
	fi

	set_terminal_title

	if ! set | grep -q '^PIMP_CALLED_VIA_DPATH_DISPLAY='
	then
		play_tonal_sound high "-${opt}"
	fi

	find -L "${dpath_music}" -type f | \
	cut -d '/' -f "$(print_cut_field_selection_number)" | sed '/^$/d' | sort -r | \
	"${_bin_fzf}" -i -s -m -e \
		--header 'pimp (file)' \
		--header-first \
		--border rounded \
		--color fg+:16,bg+:10,hl:9,hl+:1,gutter:1 \
		--prompt '> ' \
		--algo v1 \
		--query "${fzf_query}" \
		--literal \
		--cycle \
		--tac \
		--header-lines 0 \
		--layout reverse \
		--bind "backward-eof:execute-silent(pimp app-tone clsh ${fzf_opt})" \
		--bind "esc:become(printf '%s\n'    ${cmd_pimp_quit})+abort" \
		--bind "tab:become(printf '%s\n'    ${cmd_pimp_quit})+abort" \
		--bind "insert:become(printf '%s\n' ${cmd_pimp_quit})+abort" \
		--bind "alt-q:become(printf '%s\n'  ${cmd_pimp_quit})+abort" \
		--bind "ctrl-q:become(printf '%s\n' ${cmd_pimp_quit})+abort" \
		--bind "f5:become(printf '%s\n'     ${cmd_pimp_quit})+abort" \
		--bind "f6:become(printf '%s\n'     ${cmd_pimp_resume_pback})+abort" \
		--bind "f7:become(printf '%s\n'     ${cmd_pimp_refresh})+abort" \
		--bind "*:become(printf '%s\n'      ${cmd_pimp_resume_pback})+abort" \
		--bind 'enter:select-all+accept' \
		--bind 'double-click:select-all+accept' \
		--bind 'change:first' \
		--bind 'alt-bspace:clear-query' \
		--bind 'home:first' \
		--bind 'end:last' | ( \

		#  until `fzf` intuitively enables the processing of multi-line
		#  output, a while-read subshell, along with case and return
		#  statements, must be facilitated to mimic said program as it
		#  would normally behave (when handling single-line output).

		while read -r f
		do
			if [ ${i} -eq 0 ]
			then
				case "${f}" in
					"${cmd_pimp_quit}")
						return 10
						;;
					"${cmd_pimp_refresh}")
						return 20
						;;
					"${cmd_pimp_resume_pback}")
						return 30
						;;
					*)
						rm -f "${fpath_state_plist}"
						;;
				esac
			fi

			if [ ${i} -eq 200 ]  #  if 200th playlist item is processed (indicating playback delay).
			then
				play_tonal_sound ffpi "${fzf_opt}" &
			fi

			#  create absolute path and add to playlist file:
			printf '%s/%s\n' "${dpath_music}" "${f}" >> "${fpath_state_plist}"

			local i=$((i + 1))

			continue
		done

		return 0
	)

	case "$?" in
		10)
			return 0
			;;
		20)
			return 100
			;;
		30)
			play_music "${fzf_opt}"
			return 100
			;;
		*)
			local int_modtime_plist_pstloop="$(get_file_modtime "${fpath_state_plist}")"

			if [ "${int_modtime_plist_pstloop}" != "${int_modtime_plist_preloop}" ]
			then
				remove_playback_position_data
				play_music -s "${fzf_opt}"
				return 100
			else
				return 0
			fi
	esac
}

get_file_modtime()
{
	#  synopsis:  gets unix epoch modification timestamp of a file.

	local f="$1"
	local modtime=
	local sys="${_sys}"

	if ! [ -f "${f}" ]
	then
		printf 0
		return 1
	fi

	case "${sys}" in
		linux)
			local modtime="$(stat -c %Y "${f}")"
			printf '%s' "${modtime}"
			;;
		darwin|openbsd|*)
			local modtime="$(stat -f %m "${f}")"
			printf '%s' "${modtime}"
			;;
	esac

	return 0
}

play_music()
{
	#  synopsis:  plays contents of generated playlist file.

	local opt="$(_params_opt "$*")"
	local str="$(_params_str "$*")"
	local sys="${_sys}"

	if _enabled_debug
	then
		printf 'func play_music opt: %s<\n' "${opt}"
		printf 'func play_music str: %s<\n' "${str}"
		printf 'func play_music sys: %s<\n' "${sys}"
	else
		clear
	fi

	local dpath_confg="${PIMP_DPATH_CONFG}"
	local dpath_dname_fzf_selection=
	local dpath_music="${PIMP_DPATH_MUSIC}"
	local dpath_share="${PIMP_DPATH_SHARE}"
	local dpath_state="${PIMP_DPATH_STATE}"
	local dpath_state_pback="${PIMP_DPATH_STATE_PBACK}"

	local fpath_confg_pback_input="${dpath_confg}/input.conf"
	local fpath_share_script_pback_autosave="${dpath_share}/autosave.lua"
	local fpath_state_plist="${PIMP_FPATH_STATE_PLIST}"

	if _exists_opt d "${opt}" && [ -n "${str}" ]
	then
		#  create playlist file using show_dname_fzf selection.

		if [ -d "${dpath_music}/${str}" ]
		then
			local dpath_dname_fzf_selection="$(realpath "${dpath_music}/${str}")"
			find -L "${dpath_dname_fzf_selection}" -type f > "${fpath_state_plist}"
		else
			return 1
		fi
	fi

	if ! [ -f "${fpath_share_script_pback_autosave}" ]
	then
		if ! print_playback_position_autosave_script > "${fpath_share_script_pback_autosave}"
		then
			printf 'pimp: unable to create playback position auto-save script: %s\n' "${fpath_share_script_pback_autosave}" >&2
		fi
	fi

	if ! [ -f "${fpath_confg_pback_input}" ]
	then
		if ! touch "${fpath_confg_pback_input}"
		then
			printf 'pimp: unable to create playback input configuration file: %s\n' "${fpath_confg_pback_input}" >&2
		fi
	fi

	if [ -f "${fpath_state_plist}" ]
	then

		if _exists_opt s "${opt}"
		then
			#  shuffle playlist file content.
			sort -R "${fpath_state_plist}" -o "${fpath_state_plist}"
		fi

		case "${sys}" in
			darwin|linux)
				printf '%spimp: initiating the slap... (⌐■_■)%s\n' \
					"$(tput bold)" "$(tput sgr0)"
				;;
			*)
				printf '%spimp: initiating the slap...%s\n' \
					"$(tput bold)" "$(tput sgr0)"
				;;
		esac

		play_tonal_sound play "-${opt}"

		"${_bin_mus}" \
			--af-add=scaletempo=speed=both \
			--audio-pitch-correction=no \
			--display-tags= \
			--input-conf="${fpath_confg_pback_input}" \
			--loop-playlist=inf \
			--msg-level=all=no,term-msg=status,statusline=status,cplayer=error,ffmpeg=fatal,ffmpeg/demuxer=error \
			--no-audio-display \
			--no-video \
			--osd-level=0 \
			--playlist="${fpath_state_plist}" \
			--save-position-on-quit \
			--script="${fpath_share_script_pback_autosave}" \
			--term-playing-msg="\n\${filename}" \
			--term-status-msg="\n(\${playlist-pos-1}/\${playlist-count}) \${time-pos} / \${duration} (\${percent-pos}%) (x\${speed}) \${?loop-file==inf:+LF }\${?mute==yes:+M }\${?pause==yes:(Paused)}" \
			--term-title="pimp -- \${filename}" \
			--vo=null \
			--volume=100 \
			--volume-max=100 \
			--video=no \
			--watch-later-directory="${dpath_state_pback}" \
			--watch-later-options=volume,speed,pause,loop-file,start \
			--watch-later-options-remove=mute,ab-loop

		set_terminal_title
	else
		printf 'pimp: playlist file not found: %s\n' "${fpath_state_plist}" >&2
		return 2
	fi
}

play_speech()
{
	#  synopsis:  plays speech for auditory navigation.

	local opt="$(_params_opt "$*")"
	local str="$(_params_str "$*")"
	local sys="${_sys}"

	if _exists_opt Q "${opt}"
	then
		return 0
	fi

	cmd_tts()
	{
		case "${sys}" in
			darwin)
				if command -v say >/dev/null 2>&1
				then
					say -v fred -r 350 "$@"
				else
					return 1
				fi
				;;
			*)
				if command -v "${_bin_tts}" >/dev/null 2>&1
				then
					"${_bin_tts}" "$@"
				else
					return 1
				fi
				;;
		esac
	}

	str_tts()
	{
		#  removes directory path forward slashes for tts
		printf '%s' "${str}" | sed 's/\//, /g'
	}

	case "${sys}" in
		darwin)
			str_tts | cmd_tts || return 1
			;;
		linux)
			str_tts | cmd_tts -a 0100 -s 300 || return 1
			;;
		openbsd|*)
			str_tts | cmd_tts -a 0100 -s 235 || return 1
			;;
	esac

	return 0
}

play_tonal_sound()
{
	#  synopsis:  generates and plays tonal sound effects for auditory navigation.

	local opt="$(_params_opt "$*")"
	local str="$(_params_str "$*")"
	local sys="${_sys}"

	if _enabled_debug
	then
		printf 'func play_tonal_sound opt: %s<\n' "${opt}"
		printf 'func play_tonal_sound str: %s<\n' "${str}"
	fi

	if _exists_opt Q "${opt}"
	then
		return 0
	fi

	local dpath_cache="${PIMP_DPATH_CACHE}"
	local dpath_share_sound="${PIMP_DPATH_SHARE_SOUND}"
	local fpath_share_sound=

	cmd_sound_play()
	{
		play -q "$1"
	}

	case "${str}" in
		boot)
			#  pimp boot / initialization (for stereos)
			local fpath_share_sound="${dpath_share_sound}/boot.wav"

			if ! [ -f "${fpath_share_sound}" ] && command -v "${_bin_snd}" >/dev/null 2>&1
			then
				"${_bin_snd}" -n "${dpath_cache}/1.wav" \
					synth sine 1000 trim 0 0.15 gain -20 \
					pad 0 0.001 \
					gain 5

				"${_bin_snd}" -n "${dpath_cache}/2.wav" \
					synth sine 1500 trim 0 0.15 gain -20 \
					pad 0 0.001 \
					gain 5

				"${_bin_snd}" -n "${dpath_cache}/3.wav" \
					synth sine 2000 trim 0 0.15 gain -20 \
					pad 0 1 \
					gain 5

				"${_bin_snd}" \
					"${dpath_cache}/1.wav" \
					"${dpath_cache}/2.wav" \
					"${dpath_cache}/3.wav" \
					"${fpath_share_sound}"

				rm -f "${dpath_cache}/*.wav"
			fi

			cmd_sound_play "${fpath_share_sound}"
			;;
		clsh)
			#  text (search box cleared)
			local fpath_share_sound="${dpath_share_sound}/clsh.wav"

			if ! [ -f "${fpath_share_sound}" ] && command -v "${_bin_snd}" >/dev/null 2>&1
			then
				"${_bin_snd}" -n "${fpath_share_sound}" \
					synth sine 0200 trim 0 0.05 gain -20 \
					pad 0 0.1
			fi

			cmd_sound_play "${fpath_share_sound}" &
			;;
		ffpi)
			#  show_fpath_fzf playlist initialization
			local fpath_share_sound="${dpath_share_sound}/ffpi.wav"

			if ! [ -f "${fpath_share_sound}" ] && command -v "${_bin_snd}" >/dev/null 2>&1
			then
				"${_bin_snd}" -n "${dpath_cache}/1.wav" \
					synth sine 0500 trim 0 0.05 gain -20 \
					pad 0 0.05

				"${_bin_snd}" -n "${dpath_cache}/2.wav" \
					synth sine 0500 trim 0 0.05 gain -20 \
					pad 0 0.05

				"${_bin_snd}" -n "${dpath_cache}/3.wav" \
					synth sine 0500 trim 0 0.05 gain -20 \
					pad 0 1

				"${_bin_snd}" \
					"${dpath_cache}/1.wav" \
					"${dpath_cache}/2.wav" \
					"${dpath_cache}/3.wav" \
					"${fpath_share_sound}"

				rm -f "${dpath_cache}/*.wav"
			fi

			cmd_sound_play "${fpath_share_sound}" &
			;;
		ffbk)
			#  fuzzy finder (return to show_dname_fzf)
			local fpath_share_sound="${dpath_share_sound}/ffbk.wav"

			if ! [ -f "${fpath_share_sound}" ] && command -v "${_bin_snd}" >/dev/null 2>&1
			then
				"${_bin_snd}" -n "${dpath_cache}/1.wav" \
					synth sine 1500 trim 0 0.05 gain -30 \
					pad 0 0.1

				"${_bin_snd}" -n "${dpath_cache}/2.wav" \
					synth sine 1400 trim 0 0.05 gain -30 \
					pad 0 0.1

				"${_bin_snd}" \
					"${dpath_cache}/1.wav" \
					"${dpath_cache}/2.wav" \
					"${fpath_share_sound}"

				rm -f "${dpath_cache}/*.wav"
			fi

			cmd_sound_play "${fpath_share_sound}" &
			;;
		ffgo)
			#  fuzzy finder (change to show_fpath_fzf)
			local fpath_share_sound="${dpath_share_sound}/ffgo.wav"

			if ! [ -f "${fpath_share_sound}" ] && command -v "${_bin_snd}" >/dev/null 2>&1
			then
				"${_bin_snd}" -n "${dpath_cache}/1.wav" \
					synth sine 1500 trim 0 0.05 gain -30 \
					pad 0 0.1

				"${_bin_snd}" -n "${dpath_cache}/2.wav" \
					synth sine 2000 trim 0 0.05 gain -30 \
					pad 0 0.1

				"${_bin_snd}" \
					"${dpath_cache}/1.wav" \
					"${dpath_cache}/2.wav" \
					"${fpath_share_sound}"

				rm -f "${dpath_cache}/*.wav"
			fi

			cmd_sound_play "${fpath_share_sound}" &
			;;
		high)
			#  item (highlighted)
			local fpath_share_sound="${dpath_share_sound}/high.wav"

			if ! [ -f "${fpath_share_sound}" ] && command -v "${_bin_snd}" >/dev/null 2>&1
			then
				"${_bin_snd}" -n "${fpath_share_sound}" \
					synth sine 2000 trim 0 0.05 gain -30 \
					pad 0 0.1
			fi

			cmd_sound_play "${fpath_share_sound}"
			;;
		play)
			#  item (selected for music playback)
			if _exists_opt b "${opt}"
			then
				return 0
			fi

			local fpath_share_sound="${dpath_share_sound}/play.wav"

			if ! [ -f "${fpath_share_sound}" ] && command -v "${_bin_snd}" >/dev/null 2>&1
			then
				"${_bin_snd}" -n "${fpath_share_sound}" \
					synth sine 1000 trim 0 0.05 gain -30 \
					pad 0 0.1
			fi

			cmd_sound_play "${fpath_share_sound}"
			;;
	esac

	return 0
}

print_cut_field_selection_number()
{
	#  description:
	#
	#  posix solution to count number of directory levels in
	#  $PIMP_DPATH_MUSIC; facilitates removal of $PIMP_DPATH_MUSIC
	#  from fzf lists via `cut`.

	local dpath_music="${PIMP_DPATH_MUSIC}"
	local int_dpath_sections="$(( $(printf '%s' "${dpath_music}" | sed 's/\// /g' | wc -w) + 2 ))"

	printf '%s-' "${int_dpath_sections}" && \
		return 0
}

print_playback_position_autosave_script()
{
	cat <<EOF

-- autosave.lua
-- ------------
--
-- periodically saves watch_later data during mpv playback.
-- accounts for periodic write synchronization on raspberry pi.

os        = require 'os'
mp        = require 'mp'
mp_opt    = require 'mp.options'
timer_opt = {save_period = 15} -- seconds per mpv watch_later data save.
raspi     = false

function platform()

	-- gets running platform / os.

	local out = io.popen('uname -s')
	local sys = out:read '*line'

	io.close(out)
	return sys:lower()
end

function raspi_write_sync()

	-- synchronizes mpv watch_later data to raspberry pi storage device.

	local f = nil

	if raspi == true then
		os.execute('sync')
		return true
	end

	-- raspberry pi os:
	if platform() == 'linux' then
		f = io.open('/sys/firmware/devicetree/base/model', 'r')
	end

	if f ~= nil then
		str = f:read '*a'
		io.close(f)
	else
		return false
	end

	if string.match(str, '^Raspberry Pi') then
		raspi = true
		os.execute('sync')
		return true
	else
		return false
	end
end

function add_wl()
	mp.commandv('write-watch-later-config')
	raspi_write_sync()
end

function del_wl(data)
	if data.reason == 'eof' or data.reason == 'stop' then
		local playlist = mp.get_property_native('playlist')

		for i, entry in pairs(playlist) do
			if entry.id == data.playlist_entry_id then
				mp.commandv('delete-watch-later-config', entry.filename)
				raspi_write_sync()
			end
		end
	end
end

mp_opt.read_options(timer_opt)
save_period_timer = mp.add_periodic_timer(timer_opt.save_period, add_wl)

mp.register_event('file-loaded', add_wl)
mp.register_event('start-file',  add_wl)
mp.register_event('end-file',    del_wl)
EOF

	return 0
}

print_usage()
{
	#  synopsis:  prints usage information.

	print_funny_usage_header()
	{
		local int=$(awk -v min=0 -v max=4 '
			BEGIN{srand()
			print int(min+rand()*(max-min+1))
		}')

		case "${int}" in
			0)
				printf 'Show that stereo who'\''s boss.'
				;;
			1)
				printf 'Whatsup, playa!?'
				;;
			2)
				printf 'Put that stereo in its place.'
				;;
			3)
				printf 'Unleash the slap.'
				;;
			4)
				printf 'Make the whole hood jealous.'
				;;
		esac
	}

	cat <<EOF
$(print_funny_usage_header)

usage:
  pimp [d|dir] [-Q] [query]
  pimp [f|file] [-Q] [query]
  pimp [p|play|slap] [-bdQs] [path]

  pimp [app-rmpp]
  pimp [app-speech] [-Q] text
  pimp [app-tone] [-Q] clsh|ffpi|ffbk|ffgo|high|play
  pimp [splash]

commands:
  d, dir [-Q] [query]             List directories in fuzzy finder.
  f, file [-Q] [query]            List files in fuzzy finder.
  p, play, slap [-bdQs] [path]    Resume music playback.
  splash                          Display boot splash for your own project.

commands (not intended for user invocation):
  app-rmpp                                            Delete playback data.
  app-speech [-Q] text                                Play text-to-speech.
  app-tone [-Q] boot|clsh|ffpi|ffbk|ffgo|high|play    Play tonal sound.

options:
  -b           Suppress initial "play" tonal sound only once.
  -d [path]    Play relative directory path (case-sensitive).
  -Q           Suppress all auditory navigation.
  -s           Shuffle playlist file content.

environment variables:
  PIMP_DEBUG          [1|yes|true]    Prints debug output.
  PIMP_DPATH_CACHE    [path]          Path of pimp cache directory.
  PIMP_DPATH_CONFG    [path]          Path of pimp configuration directory.
  PIMP_DPATH_MUSIC    [path]          Path of music directory.
  PIMP_DPATH_SHARE    [path]          Path of pimp share directory.
  PIMP_DPATH_STATE    [path]          Path of pimp state directory.

examples:
  pimp slap                 Resume the slap (music playback).
  pimp d deep house         Search for directory containing "deep house" string.
  pimp f mixes/ fm 199      Search for files containing "fm" and "199" with
  pimp p -d hip hop/lofi    Play "hip hop/lofi" path without using fuzzy finder.
                            paths that match the "mixes/" string.
EOF

	return 1
}

remove_playback_position_data()
{
	#  synopsis:  deletes preexisting mpv watch_later / playback position data.

	set -u

	local dpath_state_pback="${PIMP_DPATH_STATE_PBACK}"

	if rm -f "${dpath_state_pback}"/* >/dev/null 2>&1
	then
		return 0
	else
		printf 'pimp: playback position data stored within "%s" could not be deleted.\n' \
			"${dpath_state_pback}" >&2
		return 1
	fi
}

set_terminal_title()
{
	printf '\033]0;pimp\007'
	return 0
}

_enabled_debug()
{
	#  synopsis:  checks for passed boolean value before displaying debugging information.

	bool="${PIMP_DEBUG}"

	case "${bool}" in
		1|true|yes)
			return 0
			;;
		*)
			return 1
			;;
	esac
}

_exists_app_dir_tree()
{
	#  synopsis:  creates application file structure.

	local dpath_cache="${PIMP_DPATH_CACHE}"
	local dpath_confg="${PIMP_DPATH_CONFG}"
	local dpath_music="${PIMP_DPATH_MUSIC}"
	local dpath_share="${PIMP_DPATH_SHARE}"
	local dpath_share_sound="${PIMP_DPATH_SHARE_SOUND}"
	local dpath_state="${PIMP_DPATH_STATE}"
	local dpath_state_pback="${PIMP_DPATH_STATE_PBACK}"

	if ! [ -d "${dpath_music}" ]
	then
		printf 'pimp: music directory not found: %s\n' "${dpath_music}" >&2
		return 2
	fi

	if ! [ -d "${dpath_cache}" ]
	then
		if ! mkdir -p "${dpath_cache}"
		then
			printf 'pimp: unable to create cache directory: %s\n' "${dpath_cache}" >&2
		fi
	fi

	if ! [ -d "${dpath_confg}" ]
	then
		if ! mkdir -p "${dpath_confg}"
		then
			printf 'pimp: unable to create configuration directory: %s\n' "${dpath_confg}" >&2
		fi
	fi

	if ! [ -d "${dpath_share}" ]
	then
		if ! mkdir -p "${dpath_share}"
		then
			printf 'pimp: unable to create share directory: %s\n' "${dpath_share}" >&2
			return 2
		fi
	fi

	if ! [ -d "${dpath_share_sound}" ]
	then
		if ! mkdir -p "${dpath_share_sound}"
		then
			printf 'pimp: unable to create sound effect directory: %s\n' "${dpath_share_sound}" >&2
			return 2
		fi
	fi

	if ! [ -d "${dpath_state}" ]
	then
		if ! mkdir -p "${dpath_state}"
		then
			printf 'pimp: unable to create state directory: %s\n' "${dpath_state}" >&2
			return 2
		fi
	fi

	if ! [ -d "${dpath_state_pback}" ]
	then
		if ! mkdir -p "${dpath_state_pback}"
		then
			printf 'pimp: unable to create playback position directory: %s\n' "${dpath_state_pback}" >&2
		fi
	fi

	return 0
}

_exists_opt()
{
	#  synopsis:  confirms existence of parameter option passed from function call.
	#
	#  usage:
	#    _exists_opt a "${string}"
	#        ^
	#        |
	#        |
	#        "a" as in an "-a" option when calling a function.
	#
	#  below, a string / $2 ("a") must match specified option / $1 ("-a").

	if printf '%s' "$2" | grep -q "$1"
	then
		return 0  #  true
	else
		return 1  #  false
	fi
}

_exists_depends()
{
	#  synopsis:  ensures program dependencies exist in $PATH.

	local err=0
	local i=               #     last program will not process without
	local programs="$* -"  #  <- placeholder at end of string.

	printf '%s' "${programs}" | tr '[:space:]' '\n' | ( \

		while read -r i
		do
			if ! command -v "${i}" >/dev/null 2>&1
			then
				if [ ${err} -eq 0 ]
				then
					printf 'pimp: prerequisite programs not found:\n' >&2
					local err=1
				fi

				printf '%s\n' " - ${i}" >&2
			fi
		done

		return "${err}"
	)

	return $?
}

_params_opt()
{
	printf '%s' "$*"          | \
	grep -o '\-[a-zA-Z0-9]*'  | \
	sed 's/-//g'              | \
	tr -d '\n'
}

_params_str()
{
	printf '%s' "$*"          | \
	sed 's/\-[a-zA-Z0-9]*//g' | \
	sed 's/^[[:space:]]*//g'  | \
	sed 's/[[:space:]]*$//g'
}

if ! _exists_depends "${_depends_dire}"
then
	exit 2
fi

if ! _exists_depends "${_depends_optional}"
then
	printf '\npimp: continuing...\n' >&2
fi

if ! _exists_app_dir_tree
then
	exit 2
fi

if _enabled_debug
then
	printf 'init cmdline: %s<\n' "$*"
	printf 'init param: %s<\n' "${_params}"
fi

case "$1" in
	app-tone)
		play_tonal_sound "${_params}"
		exit $?
		;;
	app-speech)
		play_speech "${_params}"
		exit $?
		;;
	app-rmpp)
		remove_playback_position_data
		exit $?
		;;
	d|dir)
		show_dname_fzf "${_params}"
		exit $?
		;;
	f|file)
		while :
		do
			show_fpath_fzf "${_params}"

			case "$?" in
				100)
					continue
					;;
				*)
					exit $?
					;;
			esac
		done
		;;
	h|-h|--help|help)
		print_usage
		exit $?
		;;
	p|play|slap)
		play_music "${_params}"
		exit $?
		;;
	splash)
		clear
		show_logo
		play_tonal_sound boot
		exit $?
		;;
	*)
		if [ -f "${PIMP_FPATH_STATE_PLIST}" ]
		then
			play_music "$*"
		fi

		show_dname_fzf "$*"
		exit $?
		;;
esac
