#!/usr/bin/ansible-playbook --ask-become-pass

---
- name:         install pimp on raspberry pi
  hosts:        all
  connection:   ssh
  gather_facts: yes

  vars:
    user: user
    ansible_python_interpreter: auto_silent
    ansible_user: '{{ user }}'

  tasks:
    - debug:
        msg: "host: {{ ansible_fqdn }}"

    - name: enable autologin in raspi-config
      command: raspi-config nonint do_boot_behaviour B2
      changed_when: false
      become: yes

    - name: apt update
      apt:
        update_cache: yes
      changed_when: false
      become: yes

    - name: apt install
      apt:
        name:
          - espeak
          - fzf
          - mpv
          - sox
          - tmux
        state: present
      become: yes

    - name: create pimp directories
      file:
        path: '{{ item }}'
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: u=rwx,g=,o=
      loop:
        - '{{ ansible_user_dir }}/Music'

    - name: install pimp
      copy:
        src: pimp
        dest: /usr/local/bin/pimp
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      become: yes

    - name: install pimp-login
      copy:
        src: rpi-login.sh
        dest: /usr/local/bin/pimp-login
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      become: yes

    - name: add audiodriver env var to user profile script to stop alsa errors
      lineinfile:
        path: '{{ ansible_user_dir }}/.profile'
        regexp: '^.*export AUDIODRIVER=alsa.*'
        line: 'export AUDIODRIVER=alsa'
        insertafter: EOF
        state: present
        create: true
        owner: '{{ user }}'
        group: '{{ user }}'
        mode: u=rw,g=r,o=r

    - name: add pimp-login to user profile script
      lineinfile:
        path: '{{ ansible_user_dir }}/.profile'
        regexp: '^.*pimp-login.*'
        line: 'pimp-login'
        insertafter: EOF
        state: present

